name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip==20.2.4
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -e ./
    - name: Lint with flake8
      run: |
        flake8 . --count --statistics --config=.flake8
    - name: Check code formatting with black
      run: |
        black --check ./
    - name: Test with pytest
      run: |
        pytest
